[Icon Theme]
Name=MaterialIcons
Comment=Custom material icons
Inherits=Yaru-blue,Mint-Y,Adwaita,hicolor
Directories=scalable/apps,scalable/places,scalable/mimetypes

[scalable/apps]
Size=256
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[scalable/places]
Size=256
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Size=256
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512
